<h1 style='color:Green'>Dimensionality reduction Feature Selection</h1>

# Feature Selection  

- Feature selection is the process of selecting a subset of relevant features from a larger set of features in a dataset. The goal is to identify the most informative and discriminative features that contribute significantly to the predictive power of the model. By selecting the right set of features, we can improve the model’s accuracy, reduce overfitting, and enhance interpretability.

# Dimensionality reduction   

- Dimensionality reduction refers to techniques that transform a high-dimensional dataset into a lower-dimensional representation while preserving its essential structure and characteristics. The aim is to reduce the computational complexity, improve visualization, and eliminate redundant or noisy features.

[View the PDF](./005-Dimensionality-Reduction-Feature-Selection.pdf)

In [1]:
from IPython.display import IFrame
IFrame('005-Dimensionality-Reduction-Feature-Selection.pdf', height=600, width=650)

### Let's drive into code

In [21]:
import numpy as np
import pandas as pd

In [24]:
data = pd.read_csv('train.csv')
data.shape

(2000, 21)

In [26]:
data.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [29]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [31]:
print(X.shape, y.shape)

(2000, 20) (2000,)

In [34]:
#Normalise/Standardise data 
mu = X.mean(axis=0)
sig = X.std(axis=0)

X = (X-mu)/sig

In [37]:
from sklearn.feature_selection import SelectKBest

In [39]:
best_features = SelectKBest()

In [43]:
fit = best_features.fit(X, y)

In [45]:
fit.scores_

array([3.15981575e+01, 4.76767709e-01, 4.93707801e-01, 4.28239286e-01,
       7.72181960e-01, 1.05952453e+00, 2.92299608e+00, 1.50068244e+00,
       3.59431819e+00, 2.62541515e+00, 8.25446358e-01, 1.94848418e+01,
       2.26208825e+01, 3.52011082e+03, 2.22598374e+00, 1.67099983e+00,
       1.62881131e+00, 4.57319750e-01, 1.29330223e+00, 2.84940470e-01])

In [48]:
dfcolumns = pd.DataFrame(X.columns)
dfscores = pd.DataFrame(fit.scores_)

In [50]:
featureScore = pd.concat([dfcolumns,dfscores], axis=1)

In [52]:
featureScore.columns = ['Features', 'Scores']

In [54]:
featureScore

         Features       Scores
0   battery_power    31.598158
1            blue     0.476768
2     clock_speed     0.493708
3        dual_sim     0.428239
4              fc     0.772182
5          four_g     1.059525
6      int_memory     2.922996
7           m_dep     1.500682
8       mobile_wt     3.594318
9         n_cores     2.625415
10             pc     0.825446
11      px_height    19.484842
12       px_width    22.620882
13            ram  3520.110824
14           sc_h     2.225984
15           sc_w     1.671000
16      talk_time     1.628811
17        three_g     0.457320
18   touch_screen     1.293302
19           wifi     0.284940

In [58]:
featureScore = featureScore.sort_values(by='Scores', ascending=False)

In [60]:
featureScore

         Features       Scores
13            ram  3520.110824
0   battery_power    31.598158
12       px_width    22.620882
11      px_height    19.484842
8       mobile_wt     3.594318
6      int_memory     2.922996
9         n_cores     2.625415
14           sc_h     2.225984
15           sc_w     1.671000
16      talk_time     1.628811
7           m_dep     1.500682
18   touch_screen     1.293302
5          four_g     1.059525
10             pc     0.825446
4              fc     0.772182
2     clock_speed     0.493708
1            blue     0.476768
17        three_g     0.457320
3        dual_sim     0.428239
19           wifi     0.284940

In [66]:
featureScore[:10]['Features'].values   # Top 10 features

array(['ram', 'battery_power', 'px_width', 'px_height', 'mobile_wt',
       'int_memory', 'n_cores', 'sc_h', 'sc_w', 'talk_time'], dtype=object)

In [80]:
top_10 = list(featureScore[:10]['Features'].values)
top_10

['ram',
 'battery_power',
 'px_width',
 'px_height',
 'mobile_wt',
 'int_memory',
 'n_cores',
 'sc_h',
 'sc_w',
 'talk_time']

# Model Comparison

In [74]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [76]:
model = LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [78]:
# For all 20 features of X
scores = cross_val_score(model, X, y, cv=10)
scores.mean()

0.9620000000000001

In [84]:
# For only top 10 features of X
scores = cross_val_score(model, X[top_10], y, cv=10)
scores.mean()

0.9710000000000001